spring:
  application:
    name: stockflow
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:stockflow}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:271105}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  security:
    jwt:
      secret: ${JWT_SECRET:stockflow-local-development-secret-key-change-before-production-2026}
      expiration-ms: ${JWT_EXPIRATION_MS:3600000}
