-- H2 giữ cùng UNIQUE/FK và transaction với PostgreSQL, dùng cú pháp identity/timestamp tương thích test.
CREATE TABLE order_creation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES users(id),
    request_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    order_id BIGINT UNIQUE REFERENCES orders(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_order_creation_customer_key UNIQUE (customer_id, request_key),
    CONSTRAINT ck_order_creation_key CHECK (LENGTH(TRIM(request_key)) BETWEEN 1 AND 128),
    CONSTRAINT ck_order_creation_hash CHECK (LENGTH(request_hash) = 64)
);
